name: CD — Publish Docker Image

on:
  push:
    branches: [ main ]

# Permissions pour écrire dans le registry GitHub
permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v4

            # Connexion au registry GitHub (utilise un token automatique)
            - name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            # Construit ET pousse l'image vers ghcr.io
            - name: Build and push image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    # Format : ghcr.io/username/nom-repo:tag
                    tags: ghcr.io/${{ github.repository_owner }}/hello-pipeline:latest
